package br.ufrn.edu.imd.lpii.dorabot.model;

public enum Estados {
	
	NULO, ESPERA_NOME_BEM, ESPERA_DESCRICAO_BEM, ESPERA_LOCALIZACAO_BEM, ESPERA_CATEGORIA_BEM, 
	ESPERA_NOME_LOCALIZACAO, ESPERA_DESCRICAO_LOCALIZACAO, ESPERA_NOME_CATEGORIA, ESPERA_DESCRICAO_CATEGORIA; 

}
